### ISSUE TITLE
Wands missing from Workbench

### ISSUE THREAD

**Issue by PLWatt90** [jpw1991/Friendly-Skeleton-Wand#1]
Upon updated from 1.0.7 to 1.0.8, the wand(s) are not craftable at a workbench. The following error messages are displayed in the console:

[Info   :   BepInEx] Loading [FriendlySkeletonWand 1.0.8]
[Info   :FriendlySkeletonWand.BasePlugin] FriendlySkeletonWand has landed
[Info   :FriendlySkeletonWand.BasePlugin+<>c__DisplayClass12_0] Loading ChebGonaz_DraugrArcher.prefab...
[Warning:FriendlySkeletonWand] Exception caught while adding custom creatures: System.NullReferenceException: Object reference not set to an instance of an object
  at FriendlySkeletonWand.BasePlugin+<>c__DisplayClass12_0.<AddCustomCreatures>b__0 (System.String prefabName) [0x00015] in <a528598954d342538ebd87032cf7a80b>:0
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <695d1cc93cca45069c528c15c9fdd749>:0
  at FriendlySkeletonWand.BasePlugin.AddCustomCreatures () [0x00053] in <a528598954d342538ebd87032cf7a80b>:0
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FriendlySkeletonWand.BasePlugin.AddCustomCreatures () (at <a528598954d342538ebd87032cf7a80b>:0)
FriendlySkeletonWand.BasePlugin.Awake () (at <a528598954d342538ebd87032cf7a80b>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

Currently unable to craft a new wand or spawn in said wand.

**Comment by PLWatt90** [comment]
Tried to both uninstall/reinstall mod, as well as deleting configuration before re-installing, terminal displays same error

**Comment by dizzeenr1** [comment]
I have the same problem exactly.

**Comment by PLWatt90** [comment]
It seems the issue is with using the Tunderstore Mod Manager to download and install the mod. I tried deleting the one created by the mod store, did a manual installation, and the error went away. I had tried updating to version 1.0.9 first as well, but that did not fix the issue. Same error persisted through the update initially. If you are having this issue, delete the automatically created mod folder from the profile and instead download manually the mod from the thunderstore page and drop it into the BepInEx folder as stated in the instructions. Hopefully mod store deployment will be fixed soon.

**Comment by dizzeenr1** [comment]
thanks that worked.

**Comment by jpw1991** [comment]
Hi everyone, sorry to hear you had that issue. But I'm happy you resolved it. The mod needs the specific structure preserved because it reads the `Assets` folder beside the `.dll` to retrieve its data.

**Comment by jpw1991** [comment]
I'm investigating how to fix the problem so that installing via mod manager works too. Thanks for letting me know about the issue

**Comment by jpw1991** [comment]
@PLWatt90 @dizzeenr1 I put 1.0.10 on the Thunderstore that hopefully fixes the issue. Can you please test and let me know?

**Comment by PLWatt90** [comment]
Updating from a fixed version seems to be ok. I did not test deleting the mod and cache and re-adding simply though the store. Looks like at least on my end the issue seems to be remedied. Thank you for taking the time to remedy this!
