### ISSUE TITLE
Expose item recipes to json

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/Friendly-Skeleton-Wand#11]
# Description

Right now the recipes for items like wands are hard coded:

```cs
                config.CraftingStation = "piece_workbench";
                config.AddRequirement(new RequirementConfig("Wood", 5));
```
but it is possible to expose them as JSON which will permit users further configuration options:
```json
[
  {
    "Item": "ChebGonaz_SkeletonWand",
    "Amount": 1,
    "Requirements": [
      {
        "Item": "Wood",
        "Amount": 5
      }
    ]
  }
]
```

## Info

Read [here](https://valheim-modding.github.io/Jotunn/tutorials/recipes.html) for info on how to do it.

## Attention

Somehow this needs to be a serverside thing. Client's shouldn't be able to dictate the recipe requirements of items.

**Comment by Dracbjorn** [comment]
Let's give this a shot...

**Comment by jpw1991** [comment]
Another thing I forgot to mention: the JSON files should be inside the Assets folder somewhere. Maybe something like Assets/Recipes
