### ISSUE TITLE
Spirit pylon causing an error when disabled in config

### ISSUE THREAD

**Issue by GoblinSpore** [jpw1991/Friendly-Skeleton-Wand#26]
SpiritPylonAllowed = false

causes this error to appear on game startup

[Error:Jotunn.Entities.CustomPiece] CustomPiece ChebGonaz_SpiritPylon has no PieceTable
[Warning:Jotunn.Logger] [FriendlySkeletonWand] Custom piece ChebGonaz_SpiritPylon is not valid

**Comment by Dracbjorn** [comment]
I've actually fixed this as a side-effect of exposing the pylon building materials requirements to the config in my new branch.
